apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kubevirt-hpp
  labels:
    k8s-app: kubevirt-hpp
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kubevirt-hpp
  template:
    metadata:
      labels:
        k8s-app: kubevirt-hpp
    spec:
      containers:
        - name: kubevirt-hpp-provisioner
          image: jgriffith/hpp
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PV_DIR
              value: /var/hpvolumes
#           - name: PV_RECLAIM_POLICY
#             value: Retain

          volumeMounts:
            - name: pv-volume # root dir where your bind mounts will be on the node
              mountPath: /var/hpvolumes
              #nodeSelector:
              #- name: xxxxxx
      volumes:
        - name: pv-volume
          hostPath:
            path: /var/hpvolumes
