kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-1-hpp-claim
  annotations: 
    kubevirt.io/provisionOnNode: kube-1
spec:
  storageClassName: "kubevirt-hpp"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
